name: gh-pages

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          npm install
          npm run generate-gh-pages

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: dist